name = "mehr"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "1ff650fafa5364732d872505e1add80f"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[d1_databases]]
binding = "DB"
database_name = "super_panel_db"
database_id = "a645eb67-fd4a-4a99-a38d-65e0d7d49e91"
