name = "node-edge-12"
main = "mehr-agent.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
PANEL_URL = "https://mehr.v5twycq1o.workers.dev"
CLUSTER_KEY = "mehr_sec_fc3f368b1166460a9f9d539ac729a77a_lcjowznw"
API_KEY = "mehr_sec_fc3f368b1166460a9f9d539ac729a77a_lcjowznw"
NODE_ID = "node-edge-12"

[[services]]
binding = "MASTER_SERVICE"
service = "mehr"
