name = "edge-node-1"
main = "mehr-agent.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
PANEL_URL = "https://your-panel.workers.dev"
API_KEY = "YOUR_PANEL_NODE_API_KEY"
NODE_ID = "node-1"
