name = "node1"
main = "mehr-agent.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
PANEL_URL = "https://mehr.reza5738m.workers.dev"
CLUSTER_KEY = "mehr_cluster_secret_2026"
NODE_ID = "node-1"
