account_id = "8d1b3a222f87860731bb33497221a923"
name = "mehr"
main = "_worker.js"
compatibility_date = "2024-09-01"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[d1_databases]]
binding = "IOT_DB"
database_name = "super_panel_db"
database_id = "bd011125-1316-4b6d-a39e-074f8195d6fb"
